GET http://localhost:3001/api/persons/

###

GET http://localhost:3001/api/persons/603ad6eb5056d220f2dc7b44

###

GET http://localhost:3001/info

###

DELETE http://localhost:3001/api/persons/603bd19bbe49733806a67504

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Barto Lameo",
  "number": "344-555-3345"
}